package crimsonfluff.crimsongoats.init;

import crimsonfluff.crimsongoats.CrimsonGoats;
import crimsonfluff.crimsongoats.entity.CrimsonGoatEntity;
import crimsonfluff.crimsongoats.entity.CrimsonGoatShearedEntity;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricEntityTypeBuilder;
import net.minecraft.entity.EntityDimensions;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import net.minecraft.world.World;

public class initEntities {
    public static final EntityType<CrimsonGoatEntity> GOAT_WHITE = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_white"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 0)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_ORANGE = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_orange"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 1)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_MAGENTA = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_magenta"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 2)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_LIGHT_BLUE = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_light_blue"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 3)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_YELLOW = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_yellow"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 4)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_LIME = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_lime"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 5)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_PINK = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_pink"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 6)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_GRAY = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_gray"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 7)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_LIGHT_GRAY = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_light_gray"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 8)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_CYAN = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_cyan"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 9)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_PURPLE = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_purple"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 10)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_BLUE = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_blue"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 11)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_BROWN = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_brown"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 12)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_GREEN = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_green"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 13)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_RED = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_red"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 14)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_BLACK = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_black"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 15)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatEntity> GOAT_MISSING = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_missing"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, (EntityType<CrimsonGoatEntity> p_i48552_1_, World p_i48552_2_) -> new CrimsonGoatEntity(p_i48552_1_, p_i48552_2_, 16)).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());

    public static final EntityType<CrimsonGoatShearedEntity> GOAT_MISSING_SHEARED = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_missing_sheared"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, CrimsonGoatShearedEntity::new).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
    public static final EntityType<CrimsonGoatShearedEntity> GOAT_SHEARED = Registry.register(Registry.ENTITY_TYPE, new Identifier(CrimsonGoats.MOD_ID, "goat_sheared"), FabricEntityTypeBuilder.create(SpawnGroup.CREATURE, CrimsonGoatShearedEntity::new).dimensions(EntityDimensions.fixed(0.9f, 1.3f)).build());
}
